CREATE TABLE IF NOT EXISTS zip_codes (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    code VARCHAR(10) UNIQUE NOT NULL);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    sex VARCHAR(10) NOT NULL,
    zip_code_id BIGINT,
    FOREIGN KEY (zip_code_id) REFERENCES zip_codes(id));
